### ISSUE TITLE
You don't have a link to your website's source code

### ISSUE THREAD

**Issue by AaronBenDaniel** [Benjamin-Wirz/Robotics-Blog#1]
Nowhere on your website do you link to this GitHub repo.

Here is a better _index.md file. [_index.md](https://github.com/Benjamin-Wirz/Robotics-Blog/files/14919202/_index.md)

**Comment by Benjamin-Wirz** [comment]
Suck it

**Comment by Benjamin-Wirz** [comment]
Suck it

**Comment by AaronBenDaniel** [comment]
:(
